name: Despliegue Continuo jquiroz.net

on:
  push:
    branches:
      - main

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    name: Despliegue servidor
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Ejecutar FASTAPI
      run: |
        ssh -o StrictHostKeyChecking=no toral@jquiroz.net << 'EOF'
          cd /home/toral/productos-api-front
          git pull origin main
          docker compose down -v
          docker compose up -d --build > productos-front.log
        EOF
